// Generated by scripts/generate-route-manifest.mjs. Do not edit by hand.
export const ROUTE_FILE_IDS = [
  '(auth)/_layout',
  '(auth)/login',
  '(auth)/signup',
  '(auth)/verify-email',
  '(tabs)/_layout',
  '(tabs)/profile/_layout',
  '(tabs)/profile/index',
  '(tabs)/programs/_layout',
  '(tabs)/programs/index',
  '(tabs)/tracker/_layout',
  '(tabs)/tracker/index',
  '_layout',
  'exercise/[exerciseId]',
  'exercise/index',
  'index',
  'program/[instanceId]',
  'program/editor/[definitionId]',
  'program/new',
  'sync',
  'workout/[sessionId]',
  'workout/history',
] as const;

export const PUBLIC_ROUTE_PATHS = [
  '/',
  '/exercise',
  '/exercise/[exerciseId]',
  '/login',
  '/profile',
  '/program/[instanceId]',
  '/program/editor/[definitionId]',
  '/program/new',
  '/programs',
  '/signup',
  '/sync',
  '/tracker',
  '/verify-email',
  '/workout/[sessionId]',
  '/workout/history',
] as const;

export type RouteFileId = (typeof ROUTE_FILE_IDS)[number];
export type PublicRoutePath = (typeof PUBLIC_ROUTE_PATHS)[number];
