// Generated by scripts/generate-route-manifest.mjs. Do not edit by hand.
export const ROUTE_FILE_IDS = [
  '(auth)/_layout',
  '(auth)/login',
  '(auth)/signup',
  '(auth)/verify-email',
  '(protected)/(tabs)/_layout',
  '(protected)/(tabs)/profile/_layout',
  '(protected)/(tabs)/profile/index',
  '(protected)/(tabs)/programs/_layout',
  '(protected)/(tabs)/programs/index',
  '(protected)/(tabs)/tracker/_layout',
  '(protected)/(tabs)/tracker/index',
  '(protected)/_layout',
  '(protected)/exercise/[exerciseId]',
  '(protected)/exercise/index',
  '(protected)/program/[instanceId]',
  '(protected)/program/editor/[definitionId]',
  '(protected)/program/new',
  '(protected)/sync',
  '(protected)/workout/[sessionId]',
  '(protected)/workout/history',
  '_layout',
  'index',
] as const;

export const PUBLIC_ROUTE_PATHS = [
  '/',
  '/exercise',
  '/exercise/[exerciseId]',
  '/login',
  '/profile',
  '/program/[instanceId]',
  '/program/editor/[definitionId]',
  '/program/new',
  '/programs',
  '/signup',
  '/sync',
  '/tracker',
  '/verify-email',
  '/workout/[sessionId]',
  '/workout/history',
] as const;

export type RouteFileId = (typeof ROUTE_FILE_IDS)[number];
export type PublicRoutePath = (typeof PUBLIC_ROUTE_PATHS)[number];
