// Thin barrel: Brunetti 365 phase builders + book tables + exercise map.
export {
  BOOK_JAW_B1,
  BOOK_JAW_B2,
  BOOK_JAW_B3,
  BOOK_T1_BENCH_D1,
  BOOK_T1_DL_D1,
  BOOK_T1_BOX_SQUAT,
  BOOK_PN_SQUAT_D1_MAIN,
  BOOK_PN_BENCH_D1,
  BOOK_PN_DL_D3_B1,
  BOOK_PN_BENCH_D3_B2,
  BOOK_PN_SQUAT_D1_B2,
  BOOK_IS_SQUAT_D1,
  BOOK_IS_BENCH_D1,
  FZ_EXIT_NOTES,
} from './brunetti-book-tables';

export { buildFaseZero } from './brunetti-fase-zero';
export { buildFaseT1 } from './brunetti-fase-t1';
export { buildFasePN } from './brunetti-fase-pn';
export { buildFaseJAW } from './brunetti-fase-jaw';
export { buildFaseIS } from './brunetti-fase-is';

export const BRUNETTI_EXERCISES: Record<string, Record<string, never>> = {
  squat: {},
  bench: {},
  deadlift: {},
  box_squat: {},
  front_squat: {},
  squat_bodyweight: {},
  bench_pushups: {},
  deadlift_isometric: {},
  incline_db_press: {},
  bulgarian_split_squat: {},
  bulgarian_split_squat_slow: {},
  deadlift_partial_blocks: {},
  deadlift_elevated: {},
  apert: {},
  triceps_pushdown: {},
  ext_quad: {},
  curl_fem: {},
  gemelo_pie: {},
  gemelo_sent: {},
  rear_delt_band: {},
  leg_curl_prone: {},
  curl_bar: {},
  prensa: {},
  bench_board: {},
  bench_pin: {},
  one_arm_row: {},
  seal_row: {},
  leg_press_unilateral: {},
  curl_elastico: {},
  french_press_band: {},
  french_press_bench: {},
  lateral_raise_seated: {},
  lateral_raise_band: {},
  pin_squat: {},
  plank: {},
  reverse_plank: {},
  sit_up_decline: {},
  hyperextension: {},
  calf_raise_proprioceptive: {},
  pulley_band_seated: {},
  pushup_isometric: {},
  leg_press_isometric: {},
  ohp: {},
  'goodmorning-seated': {},
};
