import type { SlotDef } from './shared';
import { NC } from './shared';

const DP_RULE = { type: 'double_progression', repRangeTop: 12, repRangeBottom: 6 } as const;

/**
 * Double progression helper for PPL A/B.
 * Single stage — weight goes up (+inc) as soon as the first set hits >= 12 reps.
 * Only the first set (index 0) determines progression.
 */
function pplAbDP(
  exerciseId: string,
  sets: number,
  inc: number,
  slotId: string,
  notes: string
): SlotDef {
  return {
    id: slotId,
    exerciseId,
    tier: 'hypertrophy',
    stages: [{ sets, reps: 6 }],
    onSuccess: DP_RULE,
    onFinalStageSuccess: { type: 'add_weight_reset_stage', amount: inc },
    onUndefined: NC,
    onMidStageFail: NC,
    onFinalStageFail: NC,
    startWeightKey: slotId,
    notes,
    progressionSetIndex: 0,
  };
}

export const PPL_AB_DEFINITION_JSONB = {
  cycleLength: 6,
  totalWorkouts: 78,
  workoutsPerWeek: 3,
  configTitle: 'Configura tus pesos iniciales',
  configDescription: 'Introduce el peso con el que quieres empezar cada ejercicio.',
  exercises: {
    bench_machine: {},
    incline_press_smith: {},
    pec_deck: {},
    lateral_raise: {},
    triceps_extension: {},
    incline_machine_press: {},
    dips: {},
    cruces: {},
    shoulder_press_machine: {},
    skullcrusher: {},
    lat_pulldown_neutral: {},
    gironda_row: {},
    machine_row: {},
    face_pull: {},
    machine_preacher_curl: {},
    machine_lat_pulldown: {},
    dbrow: {},
    t_bar_row: {},
    cable_upright_row: {},
    incline_leg_press: {},
    barbell_rdl: {},
    bulgarian_split_squat: {},
    ext_quad: {},
    gemelo_sent: {},
    hack_squat: {},
    horizontal_leg_press: {},
    hip_thrust: {},
    curl_fem: {},
    leg_press_gem: {},
    hammer_curl: {},
  },
  weightIncrements: {
    bench_machine: 2.5,
    incline_press_smith: 2.5,
    pec_deck: 2.5,
    lateral_raise: 2.5,
    triceps_extension: 2.5,
    incline_machine_press: 2.5,
    dips: 2.5,
    cruces: 2.5,
    shoulder_press_machine: 2.5,
    skullcrusher: 2.5,
    lat_pulldown_neutral: 2.5,
    gironda_row: 2.5,
    machine_row: 2.5,
    face_pull: 2.5,
    machine_preacher_curl: 2.5,
    machine_lat_pulldown: 2.5,
    dbrow: 2.5,
    t_bar_row: 2.5,
    cable_upright_row: 2.5,
    hammer_curl: 2.5,
    incline_leg_press: 2.5,
    barbell_rdl: 2.5,
    bulgarian_split_squat: 2.5,
    ext_quad: 2.5,
    gemelo_sent: 2.5,
    hack_squat: 2.5,
    horizontal_leg_press: 2.5,
    hip_thrust: 2.5,
    curl_fem: 2.5,
    leg_press_gem: 2.5,
  },
  configFields: [
    // -- Push --
    {
      key: 'bench_machine_push_a',
      label: 'Press Banca en Maquina',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Push',
    },
    {
      key: 'incline_press_smith_push_a',
      label: 'Press Inclinado en Smith',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Push',
    },
    {
      key: 'pec_deck_push_a',
      label: 'Pec Deck',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Push',
    },
    {
      key: 'lateral_raise_push_a',
      label: 'Elevaciones Laterales (Push A)',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Push',
    },
    {
      key: 'triceps_extension_push_a',
      label: 'Extension Triceps (Push A)',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Push',
    },
    {
      key: 'incline_machine_press_push_b',
      label: 'Press Inclinado en Maquina',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Push',
    },
    {
      key: 'dips_push_b',
      label: 'Fondos en Paralelas (Push B)',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Push',
    },
    {
      key: 'cruces_push_b',
      label: 'Cruces en Polea (Push B)',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Push',
    },
    {
      key: 'shoulder_press_machine_push_b',
      label: 'Press Hombro en Maquina',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Push',
    },
    {
      key: 'skullcrusher_push_b',
      label: 'Skullcrusher (Push B)',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Push',
    },
    // -- Pull --
    {
      key: 'lat_pulldown_neutral_pull_a',
      label: 'Jalon Agarre Neutro',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Pull',
    },
    {
      key: 'gironda_row_pull_a',
      label: 'Remo Gironda',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Pull',
    },
    {
      key: 'machine_row_pull_a',
      label: 'Remo en Maquina (Pull A)',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Pull',
    },
    {
      key: 'face_pull_pull_a',
      label: 'Face Pull (Pull A)',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Pull',
    },
    {
      key: 'machine_preacher_curl_pull_a',
      label: 'Curl Predicador en Maquina',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Pull',
    },
    {
      key: 'machine_lat_pulldown_pull_b',
      label: 'Jalon en Maquina',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Pull',
    },
    {
      key: 'dbrow_pull_b',
      label: 'Remo con Mancuernas (Pull B)',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Pull',
    },
    {
      key: 't_bar_row_pull_b',
      label: 'Remo en T',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Pull',
    },
    {
      key: 'cable_upright_row_pull_b',
      label: 'Remo al Menton en Polea',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Pull',
    },
    {
      key: 'hammer_curl_pull_b',
      label: 'Curl Martillo (Pull B)',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Pull',
    },
    // -- Piernas --
    {
      key: 'incline_leg_press_legs_a',
      label: 'Prensa Inclinada',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Piernas',
    },
    {
      key: 'barbell_rdl_legs_a',
      label: 'RDL con Barra (Legs A)',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Piernas',
    },
    {
      key: 'bulgarian_split_squat_legs_a',
      label: 'Zancada Bulgara (Legs A)',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Piernas',
    },
    {
      key: 'ext_quad_legs_a',
      label: 'Extension Cuadriceps (Legs A)',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Piernas',
    },
    {
      key: 'gemelo_sent_legs_a',
      label: 'Gemelo Sentado (Legs A)',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Piernas',
    },
    {
      key: 'hack_squat_legs_b',
      label: 'Hack Squat',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Piernas',
    },
    {
      key: 'horizontal_leg_press_legs_b',
      label: 'Prensa Horizontal',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Piernas',
    },
    {
      key: 'hip_thrust_legs_b',
      label: 'Hip Thrust (Legs B)',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Piernas',
    },
    {
      key: 'curl_fem_legs_b',
      label: 'Curl Femoral (Legs B)',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Piernas',
    },
    {
      key: 'leg_press_gem_legs_b',
      label: 'Prensa Gemelo (Legs B)',
      type: 'weight',
      min: 0,
      step: 2.5,
      group: 'Piernas',
    },
  ],
  days: [
    // Day 0 — Push A
    {
      name: 'Push A',
      slots: [
        pplAbDP('bench_machine', 2, 2.5, 'bench_machine_push_a', '1xF + 1xRIR 1-2'),
        pplAbDP('incline_press_smith', 2, 2.5, 'incline_press_smith_push_a', '1xF + 1xRIR 1-2'),
        pplAbDP('pec_deck', 1, 2.5, 'pec_deck_push_a', '1xRIR 2-3'),
        pplAbDP('lateral_raise', 1, 2.5, 'lateral_raise_push_a', '1xRIR 2-3'),
        pplAbDP('triceps_extension', 1, 2.5, 'triceps_extension_push_a', '1xF'),
      ],
    },
    // Day 1 — Pull A
    {
      name: 'Pull A',
      slots: [
        pplAbDP('lat_pulldown_neutral', 2, 2.5, 'lat_pulldown_neutral_pull_a', '1xF + 1xRIR 1-2'),
        pplAbDP('gironda_row', 2, 2.5, 'gironda_row_pull_a', '1xF + 1xRIR 1-2'),
        pplAbDP('machine_row', 1, 2.5, 'machine_row_pull_a', '1xRIR 2-3'),
        pplAbDP('face_pull', 1, 2.5, 'face_pull_pull_a', '1xRIR 2-3'),
        pplAbDP('machine_preacher_curl', 1, 2.5, 'machine_preacher_curl_pull_a', '1xF'),
      ],
    },
    // Day 2 — Legs A
    {
      name: 'Legs A',
      slots: [
        pplAbDP('incline_leg_press', 2, 2.5, 'incline_leg_press_legs_a', '2xRIR 1'),
        pplAbDP('barbell_rdl', 2, 2.5, 'barbell_rdl_legs_a', '2xRIR 1'),
        pplAbDP('bulgarian_split_squat', 2, 2.5, 'bulgarian_split_squat_legs_a', '2xRIR 2-3'),
        pplAbDP('ext_quad', 2, 2.5, 'ext_quad_legs_a', '2xRIR 2-3'),
        pplAbDP('gemelo_sent', 2, 2.5, 'gemelo_sent_legs_a', '2xRIR 1'),
      ],
    },
    // Day 3 — Push B
    {
      name: 'Push B',
      slots: [
        pplAbDP('incline_machine_press', 2, 2.5, 'incline_machine_press_push_b', '1xF + 1xRIR 1-2'),
        pplAbDP('dips', 2, 2.5, 'dips_push_b', '1xF + 1xRIR 1-2'),
        pplAbDP('cruces', 1, 2.5, 'cruces_push_b', '1xRIR 2-3'),
        pplAbDP('shoulder_press_machine', 1, 2.5, 'shoulder_press_machine_push_b', '1xF'),
        pplAbDP('skullcrusher', 1, 2.5, 'skullcrusher_push_b', '1xRIR 2-3'),
      ],
    },
    // Day 4 — Pull B
    {
      name: 'Pull B',
      slots: [
        pplAbDP('machine_lat_pulldown', 2, 2.5, 'machine_lat_pulldown_pull_b', '1xF + 1xRIR 1-2'),
        pplAbDP('dbrow', 2, 2.5, 'dbrow_pull_b', '1xF + 1xRIR 1-2'),
        pplAbDP('t_bar_row', 1, 2.5, 't_bar_row_pull_b', '1xRIR 2-3'),
        pplAbDP('cable_upright_row', 1, 2.5, 'cable_upright_row_pull_b', '1xRIR 2-3'),
        pplAbDP('hammer_curl', 1, 2.5, 'hammer_curl_pull_b', '1xF'),
      ],
    },
    // Day 5 — Legs B
    {
      name: 'Legs B',
      slots: [
        pplAbDP('hack_squat', 2, 2.5, 'hack_squat_legs_b', '2xRIR 1'),
        pplAbDP('horizontal_leg_press', 2, 2.5, 'horizontal_leg_press_legs_b', '2xRIR 1'),
        pplAbDP('hip_thrust', 2, 2.5, 'hip_thrust_legs_b', '2xRIR 2-3'),
        pplAbDP('curl_fem', 2, 2.5, 'curl_fem_legs_b', '2xRIR 2-3'),
        pplAbDP('leg_press_gem', 2, 2.5, 'leg_press_gem_legs_b', '2xRIR 1'),
      ],
    },
  ],
};
